export const GET_SERVICES_REQUEST_SEND = "GET_SERVICES_REQUEST_SEND";
export const POST_SERVICES_REQUEST_SEND = "POST_SERVICES_REQUEST_SEND";
export const UPDATE_SERVICES_REQUEST_SEND = "UPDATE_SERVICES_REQUEST_SEND";
export const DELETE_SERVICES_REQUEST_SEND = "DELETE_SERVICES_REQUEST_SEND";
export const SERVICES_REQUEST_FAIL = "SERVICES_REQUEST_FAIL";
export const SERVICE_BY_ID_REQUEST_FAIL = "SERVICE_BY_ID_REQUEST_FAIL";
export const SERVICES_REQUEST_SUCCESS = "SERVICES_REQUEST_SUCCESS";
export const SERVICES__BY_ID_REQUEST_SUCCESS = "SERVICES__BY_ID_REQUEST_SUCCESS";
