export const INVITATION_REQUEST_SEND = "INVITATION_REQUEST_SEND";
export const INVITATION_REQUEST_SUCCESS = "INVITATION_REQUEST_SUCCESS";
export const INVITATION_REQUEST_FAILED = "INVITATION_REQUEST_FAILED";
