export const USER_TOKEN_REQUEST = "USER_TOKEN_REQUEST";
export const USER_TOKEN_SUCCESS = "USER_TOKEN_SUCCESS";
export const USER_TOKEN_FAIL = "USER_TOKEN_FAIL";

export const USER_INFO_FAIL = "USER_INFO_FAIL";
export const USER_INFO_SUCCESS = "USER_INFO_SUCCESS";
export const USER_INFO_REQUEST = "USER_INFO_REQUEST";
export const USER_INFO_LOGOUT = "USER_INFO_LOGOUT";
